### PR TITLE
Translated to Japanese

### PR DESCRIPTION
**Pull request by jarinosuke**
Hi!

I'm one of Japannese Swifter.

About 20 days ago, I translated your awesome swift-style-guide to Japanese.
Then, many Japanese read [my translation](https://github.com/jarinosuke/swift-style-guide)!

So, I want to add it to master repository not mine because I want new swifters to read this awesome guide.

If this PR doesn't fit for you, I'm sorry about that.
Thanks!

### CODE REVIEW

**Comment by robrix** [comment]
Thank you so much for the PR! :smile: We’d love to link to the Japanese translation, but I don’t think it makes sense for it to be in this repo because we would be unable to maintain it as the English version is changed. (As background, we [discussed this when considering the Chinese translation](https://github.com/github/swift-style-guide/pull/15).)

Would you be interested in linking to your fork instead?

**Comment by jarinosuke** [comment]
@robrix Thanks for replying! and I'm sorry that I didn't review previous translation PR.

I opened new PR just added link to my repos.
https://github.com/github/swift-style-guide/pull/37

thanks!

**Comment by robrix** [comment]
No need to apologize—thank you so much for the translation and the pull request! :bow:

**Comment by jarinosuke** [comment]
@robrix Thank you so much!

**Pull request merged**
