### PR TITLE
Added a section about guard statement

### PR DESCRIPTION
**Pull request by poisonedslo**
Guard statements should be used to exit early

### CODE REVIEW

**Comment by joshaber** [comment]
:+1: 

@github/objective-c Anyone :-1: on this?

**Comment by poisonedslo** [comment]
I was just thinking, that it should probably be extended to cases other than optional unwrapping. i.e.:

```swift
guard !number.isNan else {
    return
}
//do something with number
```

**Comment by mdiep** [comment]
:+1:

**Comment by robb** [comment]
:+1:

**Comment by lfaoro** [comment]
Where is the `Code Organization` section? :dart: #46 

:+1:  for `guard`

**Comment by robrix** [comment]
I’d _much_ rather read `if number.isNan { return }` than `guard !number.isNan else { return }`. Inverting the sense of the condition confuses me, badly, every time.

**Comment by robb** [comment]
> I’d much rather read if number.isNan { return } than guard !number.isNan else { return }. Inverting the sense of the condition confuses me, badly, every time.

I had to do a double-take as well, but I think the problem is more of a poorly chosen example, something like

```Swift
guard user.admin else {
    return
}
```

might be easier on the eyes?

**Comment by kiliankoe** [comment]
> I'd probably have a `notNAN` extension if I ever needed it…

Don't mind me mixing in here, but wouldn't that be more of an `isNum` extension? :stuck_out_tongue:

**Comment by robb** [comment]
tru dat

**Comment by poisonedslo** [comment]
And of course, guard statement will produce a compile-time error without return/continue/break statement

**Comment by poisonedslo** [comment]
Decision about guard/if should be based on intention instead of need to invert the condition. That's also why I provided this example.

**Comment by joshaber** [comment]
Perhaps we should reframe this to simply be about returning early, and not about `guard` in particular. Our Objective-C style guide has a bullet point to that effect: https://github.com/github/objective-c-style-guide/blob/master/README.md

**Comment by poisonedslo** [comment]
I updated this section. Is it all right now?

**Comment by joshaber** [comment]
This looks good to me, but could you get rid of all the whitespace changes first? Thanks!

**Comment by poisonedslo** [comment]
Uh, an online editor screwed it up. I hope it's all right now

**Comment by joshaber** [comment]
That'll do, thanks!

**Pull request merged**
